version: '3.8'

services:
  anotaai_db:
    image: postgres:latest
    container_name: anotaai_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    networks:
      - anotaai_network

  anotaai_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: anotaai_backend
    restart: always
    depends_on:
      - anotaai_db
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      DB_HOST: ${DB_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules # Ignora node_modules do host
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    networks:
      - anotaai_network

  anotaai_frontend:
    image: nginx:latest
    container_name: anotaai_frontend
    restart: always
    depends_on:
      - anotaai_backend
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/share/nginx/
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - anotaai_network

networks:
  anotaai_network:
    driver: bridge

volumes:
  pgdata:

